_wandb:
    value:
        cli_version: 0.19.11
        m:
            - "1": train_step
              "6":
                - 3
              "7": []
            - "1": eval_step
              "6":
                - 3
              "7": []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 30
                - 41
                - 49
                - 53
                - 55
                - 71
                - 95
            "2":
                - 1
                - 5
                - 11
                - 30
                - 41
                - 49
                - 53
                - 55
                - 71
                - 95
            "3":
                - 7
                - 13
                - 23
                - 55
            "4": 3.12.11
            "5": 0.19.11
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
